### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by anshul12112** [matsui528/nanosearch#10]
127.0.0.1 - - [09/Apr/2019 17:20:26] "GET / HTTP/1.1" 200 -
[2019-04-09 17:20:34,386] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 31, in index
    dists = np.linalg.norm(features - query, axis=1)  # Do search
ValueError: operands could not be broadcast together with shapes (0,) (4096,) 
127.0.0.1 - - [09/Apr/2019 17:20:34] "POST / HTTP/1.1" 500 -

please sir help in resolving this issue ...i need this project urgently

**Comment by anshul12112** [comment]
please sir resolve this issue

**Comment by anshul12112** [comment]
127.0.0.1 - - [09/Apr/2019 17:24:50] "GET / HTTP/1.1" 200 -
[2019-04-09 17:24:59,066] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 31, in index
    dists = np.linalg.norm(features - query, axis=1)  # Do search
ValueError: operands could not be broadcast together with shapes (0,) (4096,) 
127.0.0.1 - - [09/Apr/2019 17:24:59] "POST / HTTP/1.1" 500 -
![Screenshot from 2019-04-09 17-25-47](https://user-images.githubusercontent.com/44797619/55798445-92039200-5aec-11e9-8a98-3f0286da6c0a.png)

**Comment by matsui528** [comment]
Cannot reproduce the problem. Please update conda, tensorflow, and keras to the latest version, and follow the instruction: https://github.com/matsui528/sis#usage

Suppose that you have `a.jpg`, `b.jpg`, and `c.jpg` on `static/img`. After your run `python offline.py`, you will have `a.pkl`, `b.pkl`, and `c.pkl` on `static/feature`.  Then `python server.py` should work.

**Comment by anshul12112** [comment]
> Cannot reproduce the problem. Please update conda, tensorflow, and keras to the latest version, and follow the instruction: https://github.com/matsui528/sis#usage
> 
> Suppose that you have `a.jpg`, `b.jpg`, and `c.jpg` on `static/img`. After your run `python offline.py`, you will have `a.pkl`, `b.pkl`, and `c.pkl` on `static/feature`. Then `python server.py` should work.

sir thank you so much you.professor like you is need of today's era . A big thank to you. you make my work easy.Always grateful to you sir

**Comment by saewitz** [comment]
My problem with this was that my images were png, not jpg, which is what offline.py is expecting.
