### ISSUE TITLE
getting server error while running server.py

### ISSUE THREAD

**Issue by khalid5454** [matsui528/nanosearch#13]
Hello.

while I do the same process and the first file is working for features extractor but when I run server.py and get a web UI then provide query image getting the following result.

##ERROR

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

###
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/Sep/2019 08:18:23] "GET / HTTP/1.1" 200 -
[2019-09-07 08:18:29,635] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Muhammad Khalid\Downloads\sis-master\server.py", line 28, in index
    img.save(uploaded_img_path)
  File "C:\Users\Muhammad Khalid\Anaconda3\lib\site-packages\PIL\Image.py", line 1991, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'static/uploaded/2019-09-07T08:18:29.575887_9171c7e3180c3c6fc59134538c01116.jpg'
127.0.0.1 - - [07/Sep/2019 08:18:29] "POST / HTTP/1.1" 500 -

any help.@matsui528

**Comment by matsui528** [comment]
See https://github.com/matsui528/sis/issues/2#issuecomment-375862362
