### ISSUE TITLE
There's something wrong about Internal Server Error.

### ISSUE THREAD

**Issue by wzc118** [matsui528/nanosearch#2]
when i press the submit button, something wrong with flask, Internal Server Error 500 happen.
this is the mistake info:
[2018-03-24 17:14:22,079] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 28, in index
    img.save(uploaded_img_path)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\PIL\Image.py", line 1890, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'static/uploaded/2018-03-24T17:14:22.047335_203006213_202149811_225504129_2017_12_28_And_1514462132702-1244746321.jpg'
127.0.0.1 - - [24/Mar/2018 17:14:22] "POST / HTTP/1.1" 500 -
[2018-03-24 17:18:22,427] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 28, in index
    img.save(uploaded_img_path)
  File "C:\Users\wzc118\Anaconda3\lib\site-packages\PIL\Image.py", line 1890, in save
    fp = builtins.open(filename, "w+b")
OSError: [Errno 22] Invalid argument: 'static/uploaded/2018-03-24T17:18:22.395500_203006213_202149811_225504129_2017_12_28_And_1514462132702-1244746321.jpg'
127.0.0.1 - - [24/Mar/2018 17:18:22] "POST / HTTP/1.1" 500 -

**Comment by matsui528** [comment]
Hi,

It seems the problem is an invalid name of the file in WIndows. Please make sure an uploaded image is correctly saved with the name `static/uploaded/2018-03-24T17:14:22.047335_203006213_202149811_225504129_2017_12_28_And_1514462132702-1244746321.jpg`  I guess a semicolon is prohibited for the filename in Windows. 

You can edit this line to some valid name, then it would work https://github.com/matsui528/sis/blob/d5c687d59a8af5b91836cd05d67a3febbde76acf/server.py#L27

**Comment by wzc118** [comment]
thx . It has fixed

**Comment by nguyennd42** [comment]
me too, 
How to fix errors? 
plsss

**Comment by khalid5454** [comment]
how you fix it, what changes you have done.
can you give me an example. @wzc118 wzc118

**Comment by khalid5454** [comment]
I change this line from 
 uploaded_img_path = "static/uploaded/" + datetime.now().isoformat() + " _" + file.filename 
#TO 
  uploaded_img_path = "static/uploaded/"  + " _" + file.filename 

#It working
but I am not getting the first two pics, like if I pass 10 value so the first two is missing and 8 are recommended ... 
# Sometimes it is working like recommend the exact amount of images 

#Code--------------------------

 img = Image.open(file.stream)  # PIL image
        uploaded_img_path: Union[str, Any] = "static/uploaded/"+ "_" + file.filename
        img.save(uploaded_img_path)

        query = fe.extract(img)
        dists = np.linalg.norm(features - query, axis=1)  # Do search
        ids = np.argsort(dists)[:10]  # Top 10 results
        scores = [(dists[id], img_paths[id]) for id in ids]

##-----------------------------------
WHY I am not getting first two recommended pictures.
##Any Solution 
@wzc118 @matsui528

**Comment by matsui528** [comment]
I guess it doesn't work if `file.filename` is same for two images. Please try this:
```
uploaded_img_path = "static/uploaded/" + datetime.now().strftime('%Y_%m_%d_%H_%M_%S') + "_" + file.filename
```

**Comment by khalid5454** [comment]
Thanks
