### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by rbreve** [matsui528/nanosearch#6]
Getting this error

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 30, in index
    query = fe.extract(img)
  File "/Users/rbreve/Developer/opencv/sis/feature_extractor.py", line 18, in extract
    feature = self.model.predict(x)[0]  # (1, 4096) -> (4096, )
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1832, in predict
    self._make_predict_function()
  File "/usr/local/lib/python2.7/site-packages/keras/engine/training.py", line 1031, in _make_predict_function
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2506, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 2449, in __init__
    with tf.control_dependencies(self.outputs):
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 5027, in control_dependencies
    return get_default_graph().control_dependencies(control_inputs)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 4631, in control_dependencies
    c = self.as_graph_element(c)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3590, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3669, in _as_graph_element_locked
    raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("fc1/Relu:0", shape=(?, 4096), dtype=float32) is not an element of this graph.
127.0.0.1 - - [23/May/2018 12:16:20] "POST / HTTP/1.1" 500 -

**Comment by shiv19** [comment]
Facing the same error. Any solution for this?

**Comment by rbreve** [comment]
I solved it by addig this 2 lines on the extract method from feature_extractor.py

```
def extract(img):
    global graph
    with graph.as_default():
        img = img.resize((224, 224))  # VGG must take a 224x224 img as an input
```

**Comment by matsui528** [comment]
Hi @rbreve and @shiv19,
Sorry for my late response. I updated the code and now it should work. It seems there is a long discussion about this issue https://github.com/keras-team/keras/issues/2397

**Comment by anshul12112** [comment]
127.0.0.1 - - [09/Apr/2019 17:20:26] "GET / HTTP/1.1" 200 -
[2019-04-09 17:20:34,386] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
response = self.full_dispatch_request()
File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/home/anshul/.local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
raise value
File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
rv = self.dispatch_request()
File "/home/anshul/.local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
return self.view_functionsrule.endpoint
File "server.py", line 31, in index
dists = np.linalg.norm(features - query, axis=1) # Do search
ValueError: operands could not be broadcast together with shapes (0,) (4096,)
127.0.0.1 - - [09/Apr/2019 17:20:34] "POST / HTTP/1.1" 500 -

please sir help in resolving this issue ...i need this project urgently

**Comment by vinaychetu** [comment]
Hi Everyone,
I have the error in SIS (image search engine) like below.
raise ValueError("Tensor %s is not an element of this graph." % obj)
ValueError: Tensor Tensor("fc1/Relu:0", shape=(?, 4096), dtype=float32) is not an element of this graph.
 
Then I change the code of feature_extractor.py as below and now it works fine.

from keras.preprocessing import image
from keras.applications.vgg16 import VGG16, preprocess_input
from keras.models import Model
import numpy as np
import tensorflow as tf


class FeatureExtractor:
    def __init__(self):
        base_model = VGG16(weights='imagenet')
        self.model = Model(inputs=base_model.input, outputs=base_model.get_layer('fc1').output)
        self.graph = tf.get_default_graph()

    def extract(self, img):  # img is from PIL.Image.open(path) or keras.preprocessing.image.load_img(path)
        img = img.resize((224, 224))  # VGG must take a 224x224 img as an input
        img = img.convert('RGB')  # Make sure img is color
        x = image.img_to_array(img)  # To np.array. Height x Width x Channel. dtype=float32
        x = np.expand_dims(x, axis=0)  # (H, W, C)->(1, H, W, C), where the first elem is the number of img
        x = preprocess_input(x)  # Subtracting avg values for each pixel

        with self.graph.as_default():
            feature = self.model.predict(x)[0]  # (1, 4096) -> (4096, )
            return feature / np.linalg.norm(feature)  # Normalize
